import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Assistant from './components/Assistant'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Babar Mehmood - Web Developer , Programmer , ML Enthusiast',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <Assistant />
      
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
